package identification_of_rice.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.name
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.headimg
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String headimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ctime
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String reply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.name
     *
     * @return the value of comment.name
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.name
     *
     * @param name the value for comment.name
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.headimg
     *
     * @return the value of comment.headimg
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.headimg
     *
     * @param headimg the value for comment.headimg
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ctime
     *
     * @return the value of comment.ctime
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ctime
     *
     * @param ctime the value for comment.ctime
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply
     *
     * @return the value of comment.reply
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply
     *
     * @param reply the value for comment.reply
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    public Comment(Integer cid, String name, String headimg, Date ctime, Integer userid, String content, String reply) {
        this.cid = cid;
        this.name = name;
        this.headimg = headimg;
        this.ctime = ctime;
        this.userid = userid;
        this.content = content;
        this.reply = reply;
    }
}