package identification_of_rice.pojo;

public class Pest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.pestid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private Integer pestid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.kind
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private Integer kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.name
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.place
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.time
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.content
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.infourl
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String infourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.info
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.basic
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String basic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.bio
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String bio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pest.agr
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    private String agr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.pestid
     *
     * @return the value of pest.pestid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public Integer getPestid() {
        return pestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.pestid
     *
     * @param pestid the value for pest.pestid
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setPestid(Integer pestid) {
        this.pestid = pestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.kind
     *
     * @return the value of pest.kind
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.kind
     *
     * @param kind the value for pest.kind
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.name
     *
     * @return the value of pest.name
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.name
     *
     * @param name the value for pest.name
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.place
     *
     * @return the value of pest.place
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.place
     *
     * @param place the value for pest.place
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.time
     *
     * @return the value of pest.time
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.time
     *
     * @param time the value for pest.time
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.content
     *
     * @return the value of pest.content
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.content
     *
     * @param content the value for pest.content
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.infourl
     *
     * @return the value of pest.infourl
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getInfourl() {
        return infourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.infourl
     *
     * @param infourl the value for pest.infourl
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setInfourl(String infourl) {
        this.infourl = infourl == null ? null : infourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.info
     *
     * @return the value of pest.info
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.info
     *
     * @param info the value for pest.info
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.basic
     *
     * @return the value of pest.basic
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getBasic() {
        return basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.basic
     *
     * @param basic the value for pest.basic
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setBasic(String basic) {
        this.basic = basic == null ? null : basic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.bio
     *
     * @return the value of pest.bio
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.bio
     *
     * @param bio the value for pest.bio
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pest.agr
     *
     * @return the value of pest.agr
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public String getAgr() {
        return agr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pest.agr
     *
     * @param agr the value for pest.agr
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    public void setAgr(String agr) {
        this.agr = agr == null ? null : agr.trim();
    }
}