package identification_of_rice.mapper;

import com.school.identification_of_rice.pojo.Pest;
import com.school.identification_of_rice.pojo.PestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int countByExample(PestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int deleteByExample(PestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int deleteByPrimaryKey(Integer pestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int insert(Pest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int insertSelective(Pest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    List<Pest> selectByExample(PestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    Pest selectByPrimaryKey(Integer pestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int updateByExampleSelective(@Param("record") Pest record, @Param("example") PestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int updateByExample(@Param("record") Pest record, @Param("example") PestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int updateByPrimaryKeySelective(Pest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pest
     *
     * @mbggenerated Sat Nov 05 20:30:53 CST 2022
     */
    int updateByPrimaryKey(Pest record);

    List<Pest> listAll();
}